services:
  - type: web
    name: pokemon-cards-api
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        value: "Server=DESKTOP-UOPVNVH;Database=db_tcgpokemon_cards;User Id=api_user;Password=SenhaForte123@;Encrypt=True;"
